baseURL = "https://log.sbond.co/"
languageCode = "en-gb"
title = "sbondLog"
metaDataFormat = "toml"
pygmentsUseClasses = true
summaryLength = "55"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[Permalinks]
    post = "post/:slug"

[params]
    description = "sbondo's log"
    twitter = "sbondoGaming"

[[params.menu]]
    name = "Log"
    url = "l/"

[[params.menu]]
    name = "Categories"
    url = "categories/"

[privacy]
    [privacy.twitter]
        enableDNT = true
    [privacy.youtube]
        privacyEnhanced = true

[markup.goldmark.renderer]
    unsafe = true

[outputs]
    home = ["HTML", "JSON"]